# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-19 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
